import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BookingModal from "./components/BookingModal";
import { BsTelephone } from "react-icons/bs";
import { MdMailOutline } from "react-icons/md";
import { SiInstagram } from "react-icons/si";
import { FaTiktok } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  {children}
  <BookingModal />

  <footer
    style={{
      background:
        "linear-gradient(to right, #1c140f, #2b1d16)",
      color: "#f5ede6",
      padding: "90px",
      marginTop: "120px",
    }}
  >
    <div
  style={{
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "24px",
    alignItems: "start",
    width: "100%",
    margin: "0 auto",
  }}
    >
      {/* LOGO */}
      <div
  style={{
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  }}
>
  <h1
    style={{
      fontSize: "42px",
      fontWeight: "300",
      letterSpacing: "12px",
      color: "#f5ede6",
      marginBottom: "6px",
      margin: 0,
    }}
  >
    ETERNA
  </h1>

  <p
    style={{
      fontSize: "12px",
      letterSpacing: "6px",
      color: "#cbb9ad",
      marginTop: "8px",
      marginBottom: 0,
    }}
  >
    MEMORIES
  </p>
</div>

      {/* NAVIGATION */}
      <div>
        <div
          style={{
            marginBottom: "22px",
            letterSpacing: "3px",
            fontSize: "15px",
            fontWeight: 500,
            color: "#f5ede6",
          }}
        >
          НАВИГАЦИЯ
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "14px",
            color: "#d8cfc6",
          }}
        >
          <a href="/" className="footer-link">
            Начало
          </a>

          <a href="/video-booth" className="footer-link">
            Видео будка
          </a>

          <a href="/video-album" className="footer-link">
            Видео албум
          </a>

          <a href="/gallery" className="footer-link">
            Галерия
          </a>

          <a href="/contact" className="footer-link">
            Контакт
          </a>
        </div>
      </div>

      {/* CONTACT */}
      <div>
        <div
          style={{
            marginBottom: "22px",
            letterSpacing: "3px",
            fontSize: "15px",
            fontWeight: 500,
            color: "#f5ede6",
          }}
        >
          КОНТАКТИ
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "18px",
          }}
        >
          <a
            href="tel:+359888887763"
            className="footer-link"
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
            }}
          >
            <BsTelephone />
            <span>+359888887763</span>
          </a>

          <a
            href="mailto:eternamemories.bg@gmail.com"
            className="footer-link"
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
            }}
          >
            <MdMailOutline />
            <span>eternamemories.bg@gmail.com</span>
          </a>

          <a
            href="https://instagram.com/eterna__memories"
            className="footer-link"
            target="_blank"
            rel="noreferrer noopener"
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
            }}
          >
            <SiInstagram />
            <span>@eterna__memories</span>
          </a>

          <a
            href="https://tiktok.com/@eterna.memories"
            className="footer-link"
            target="_blank"
            rel="noreferrer noopener"
            style={{
              display: "flex",
              alignItems: "center",
              gap: "12px",
            }}
          >
            <FaTiktok />
            <span>@eterna.memories</span>
          </a>
        </div>
      </div>

      {/* COPYRIGHT */}
      <div
        style={{
          color: "#d8cfc6",
          lineHeight: "1.8",
          textAlign: "left",
          marginTop: "28px",
          marginLeft: "60px",
        }}
      >
        <div style={{ whiteSpace: "nowrap" }}>© 2026 ETERNA</div>
        <div>All rights reserved.</div>
      </div>
    </div>
  </footer>
</body>
</html>
  );
}